pipeline {
    agent any

    tools{
        maven 'maven3'
    }

    environment {
        // we need to add sonarqube tool name
        SCANNER_HOME = tool 'sonarqube-scanner'
    }

    parameters {
      choice choices: ['create', 'delete'], description: 'we are stopping the containers to run new build again', name: 'action'
    }


    stages {

        stage('clone'){
            when { expression { return params.action == 'create' } }
            steps {
                git 'https://github.com/VootlaSaiCharan/java-cicd-argo.git'
            }
        }

        stage('maven compile'){
            when { expression { return params.action == 'create' } }
            steps{
                script{
                    sh 'cd java-webapplication && mvn clean compile'
                }
            }
        }

        stage('Sonarqube analysis'){
            when { expression { return params.action == 'create' } }
            steps{
                // insted of adding sonar credential provide the sonarserver name in that we have already configured the sonar credentials
                withSonarQubeEnv('sonar-server') {
                    sh ''' cd java-webapplication && $SCANNER_HOME/bin/sonar-scanner -Dsonar.projectName=Java-cicd-argo \
                    -Dsonar.java.binaries=. \
                    -Dsonar.projectKey=Java-cicd-argo '''
                }
            }
        }

        stage('Creating a Image'){
            when { expression { return params.action == 'create' } }
            steps{
                script {
                    // Define the Docker image tag using BUILD_NUMBER to create version tags like v1, v2, v3, etc.
                    def DOCKER_IMAGE = "vootlasaicharan/java-cicd-argo:${BUILD_NUMBER}"
                    
                    // Build the Docker image using the dynamic version
                    sh "cd java-webapplication && docker buildx build -t ${DOCKER_IMAGE} ."
                }
            }
        }
        
        stage('push to docker hub'){
            when { expression { return params.action == 'create'} }
            steps{
                script{
                    // Define the Docker image tag using BUILD_NUMBER to create version tags like v1, v2, v3, etc.
                    def DOCKER_IMAGE = "vootlasaicharan/java-cicd-argo:${BUILD_NUMBER}"

                    // Using the withDockerRegistry step to authenticate and push the image
                    withDockerRegistry(credentialsId: 'dockerhub-cred') {
                        sh "docker push ${DOCKER_IMAGE}"
                    }
                }
            }
        }
        
        stage('Running Container'){
            when{ expression { return params.action == 'create' } }
            steps {
                script {
                    // Define the Docker image tag using BUILD_NUMBER to create version tags like v1, v2, v3, etc.
                    def DOCKER_IMAGE = "vootlasaicharan/java-cicd-argo:${BUILD_NUMBER}"
                    
                    // Run the container using the created image
                    sh "docker run --rm -itd -p 80:8080 ${DOCKER_IMAGE}"
                }
            }
        }

        stage('update the deployment file'){
            when { expression { return params.action == 'create' } }
            steps{
                script {
                    def DOCKER_IMAGE = "vootlasaicharan/java-cicd-argo:${BUILD_NUMBER}"
                    def DEPLOYMENT_FILE = "java-webapplication-manifest/deployment.yaml"

                    // Update the deployment file with the new image version
                    sh """
                        sed -i 's|image: vootlasaicharan/java-cicd-argo:.*|image: ${DOCKER_IMAGE}|g' ${DEPLOYMENT_FILE}
                    """
                    
                    withCredentials([string(credentialsId: 'github-cred', variable: 'github-cred')]) {
                        // Commit and push the changes to the repository
                        sh """
                            git config user.name "vscharan"
                            git config user.email "charanv369@gmail.com"
                            git add ${DEPLOYMENT_FILE}
                            git commit -m "Updated deployment image to ${DOCKER_IMAGE}"
                            git push origin master
                        """
                    }
                }
            }
        }
        stage('stop container'){
            when { expression { return params.action == 'delete' }}
            steps{
                script{
                    sh 'docker stop $(docker ps -aq)'
                }
            }
        }
    }
}