apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: my-app
spec:
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-container
          image: vootlasaicharan/java-cicd-argo:3
          ports:
          - containerPort: 8080
  selector:
    matchLabels:
      app: my-app
  replicas: 2
