apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: my-app
spec:
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-container
          image: vootlasaicharan/java-cicd-argo:23
          ports:
          - containerPort: 8080
  selector:
    matchLabels:
      app: my-app
  replicas: 2
  
---
apiVersion: apps/v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30005
  selector:
    app: my-app

